dist: xenial   # required for Python >= 3.7
language: python
python:
  - '3.6'

# To install packages which are not on pip
#before_install:
#  - sudo apt-get install ...
#addons:
#  apt:
#    update: true

# command to install dependencies
install:
  - pip install -r app/requirements.txt
  - pip install -r tests/test_requirements.txt

# commands to run tests
jobs:
  include:
    - stage: "Tests"                # naming the Tests stage
      name: "Linting Tests"            # names the first Tests stage job
      script: flake8
      script: pylint */*.py
# for later stages
      script: pytest

# blocklist
#branches:
#  except:
#  - branch_name1
#  - branch_name2

# safelist
#branches:
#  only:
#  - branch_name1
#  - branch_name2
